# Generated by Django 4.1.4 on 2023-01-17 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='crear_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
