# Generated by Django 4.1.4 on 2023-01-17 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_crear_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='crear_date',
            new_name='create_date',
        ),
    ]
