# Generated by Django 4.1.4 on 2023-01-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='cv',
            field=models.FileField(default='', help_text='Upload you CV', upload_to='cv'),
            preserve_default=False,
        ),
    ]
