# Generated by Django 4.1.4 on 2023-01-15 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='cv',
            field=models.FileField(help_text='upload you cv', upload_to='cv'),
        ),
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='experience',
            name='year',
            field=models.IntegerField(),
        ),
    ]
