# Generated by Django 4.1.4 on 2023-01-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_about_cv_alter_education_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='last',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='last',
        ),
    ]
