# Generated by Django 4.1.4 on 2023-01-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_remove_education_last_remove_experience_last'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('-year',)},
        ),
    ]
